# https://www.appveyor.com/docs/lang/nodejs-iojs/
version: "{build}"

shallow_clone: true

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "15"
    - nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  # - npm ci
  - yarn install

  # https://www.appveyor.com/docs/build-configuration/#configuring-build
build: off

build_script:
  # - npm run devBuild
  - yarn build

test_script:
  - node --version && npm --version
  # - npm test
  - yarn test
